name: CI Ogreniyorum

on:
  push:
    branches: [ "main" ]

jobs:
  calistir:
    runs-on: ubuntu-latest

    steps:
      - name: Repoâ€™yu al
        uses: actions/checkout@v4

      - name: Mesaj yaz
       run: exit 1
